"""Byte-identity gate for the whetstone extraction.

The fixture was generated by whetstone's Stage 0 golden baseline against
the pre-extraction `graph/` package. dr-graph must reproduce both the
canonical payload string and the digest byte-for-byte. Never regenerate
this fixture to paper over a mismatch — a failure here means the
extraction changed spec identity.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest
from dr_serialize import canonical_json

from dr_graph import GraphSpec, canonical_graph_payload, graph_digest

FIXTURE_PATH = (
    Path(__file__).parent / "fixtures" / ("graph_digests_golden.json")
)


def load_fixture() -> dict[str, dict[str, str]]:
    return json.loads(FIXTURE_PATH.read_text())


@pytest.mark.parametrize("name", sorted(load_fixture()))
def test_golden_graph_digest_reproduces(name: str) -> None:
    entry = load_fixture()[name]
    payload = json.loads(entry["canonical_payload"])
    spec = GraphSpec.model_validate(payload["graph"])

    assert (
        canonical_json(canonical_graph_payload(spec))
        == (entry["canonical_payload"])
    )
    assert graph_digest(spec) == entry["digest"]
